// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"g9ty4zg639","name":"Pets","description":"","endpoint":"https://g9ty4zg639.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:1b69bf3f-1f27-463d-a727-4facbf3310a8',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'artsnap-hosting-mobilehub-1207532684',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3v8wxn3pwjtzp.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"artsnap-mobilehub-1207532684-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"petId"}],
    'aws_mobile_analytics_app_id': 'bd16648a966e4daf94ea5f416a4a027a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '6e9582d2-88bd-4fc8-a99e-62dfb46b2424',
    'aws_project_name': 'art_snap',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'artsnap-deployments-mobilehub-1207532684',
    'aws_resource_name_prefix': 'artsnap-mobilehub-1207532684',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'artsnap-userfiles-mobilehub-1207532684',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_fcHfegQcX',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5sq5oafjqfal5i2a0rojnu0c3i',
}

export default awsmobile;
